[build]
  command = "pnpm build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

# Enable Next.js runtime for API routes
[functions]
  node_bundler = "esbuild"